version: "3"
services:
  gatsby-server:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gatsby-website:/app:rw

