version: "3"
services:
  gatsby-server:
    platform: linux/amd64
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gatsby-website:/app:rw
    environment:
     - NODE_ENV=serve #or develop
     - WEBSITE=website1 #name of the direcotry inside gatsby-website, you can use gatby new command.

